version: 0.2
phases:
  build:
    commands:
      - echo "Entered the build phases"
      - cd stock-trades-analytics/
      - mvn clean package
  post_build:
    commands:
       - echo "stock-trades application build successfully generated."
artifacts:
  files:
      - stocktrades.jar
  discard-paths: yes
